#!/bin/bash

# ----------------------------------------------------------------------------
# Restore latest mongodb dump files for the current Google Cloud VM container
# that were generated by running db-dump-google.sh.
#
# Google mongodb dump files for the render and match databases are expected to be in:
#   /mnt/disks/mongodb_dump_fs/dump/${HOSTNAME}/${RUN_TIMESTAMP}.${DB}.dump.gz
#
# If an argument is provided, it is used instead of the current hostname as the subdirectory
# (e.g. if you want to load dump files taken from a different VM).

set -e

DUMP_SUBDIR="${1:-${HOSTNAME}}/archives"
BASE_DUMP_DIR="/mnt/disks/mongodb_dump_fs/dump"

if [ ! -d "${BASE_DUMP_DIR}" ]; then
  echo "ERROR: ${BASE_DUMP_DIR} not found"
  exit 1
fi

# /mnt/disks/mongodb_dump_fs/dump/render-ws-mongodb-8c-32gb-aab
DUMP_DIR="${BASE_DUMP_DIR}/${DUMP_SUBDIR}"

if [ ! -d "${DUMP_DIR}" ]; then
  echo "ERROR: ${DUMP_DIR} not found"
  exit 1
fi

# dump files have the format: ${RUN_TIMESTAMP}.${DB}.dump.gz
#   20250204_020219.match.dump.gz
#   20250204_020219.render.dump.gz
LATEST_DUMP=$(find "${DUMP_DIR}" -type f -name "*.dump.gz" | sort | tail -n 1)
if [ ! -f "${LATEST_DUMP}" ]; then
  echo "ERROR: no dumps found in ${DUMP_DIR}"
  exit 1
fi

LATEST_TIMESTAMP=$(basename "${LATEST_DUMP}" | cut -d. -f1)

URI="mongodb://localhost:27017"

for DB in render match; do
  DUMP_FILE="${DUMP_DIR}/${LATEST_TIMESTAMP}.${DB}.dump.gz"
  if [ -f "${DUMP_FILE}" ]; then
    echo "restoring ${DUMP_FILE} ..."
    # see https://www.mongodb.com/docs/database-tools/mongorestore/
    mongorestore --uri="${URI}" --archive="${DUMP_FILE}" --gzip
  else
    echo "WARNING: ${DUMP_FILE} not found"
  fi
done
