#!/bin/bash

# ----------------------------------------------------------------------------
# Restore Janelia mongodb dump files generated by db-dump-janelia.sh
# to the database running on the current Google Cloud VM container.
#
# You will be prompted to select the dump directory within
# /mnt/disks/mongodb_dump_fs/dump/janelia to restore.

set -e

if [ $# -gt 0 ]; then
  DUMP_PATTERN="*${1}*"
else
  DUMP_PATTERN="*"
fi

BASE_DUMP_DIR="/mnt/disks/mongodb_dump_fs/dump"

if [ ! -d "${BASE_DUMP_DIR}" ]; then
  echo "ERROR: ${BASE_DUMP_DIR} not found"
  exit 1
fi

# /mnt/disks/mongodb_dump_fs/dump/janelia/20250201_094952/render/admin__stack_meta_data.bson.gz
mapfile -t DUMP_DIRECTORIES < <(find "${BASE_DUMP_DIR}" -name "${DUMP_PATTERN}.bson.gz" -type f -exec dirname {} \; | sort -u)
if [ ${#DUMP_DIRECTORIES[@]} -eq 0 ]; then
    echo "ERROR: no dump files found in ${BASE_DUMP_DIR}"
    exit 1
fi

for i in "${!DUMP_DIRECTORIES[@]}"; do
  printf " %2d) %s\n" "$((i+1))" "${DUMP_DIRECTORIES[$i]}"
done
echo

read -rp "Enter the numbers of the dump directories you want to restore (space-separated): " CHOICES
# shellcheck disable=SC2086
set -- ${CHOICES}
DUMP_DIR_NUMS=("$@")

if (( ${#DUMP_DIR_NUMS[@]} == 0 )); then
    printf "\nExiting, no choice entered\n\n"
    exit 1
fi

SELECTED_DIRS=()
for n in "${DUMP_DIR_NUMS[@]}"; do
  if [[ ! "$n" =~ ^[0-9]+$ ]]; then
    echo "ERROR: '$n' is not a number" >&2
    exit 1
  fi
  idx=$((n-1))
  if (( idx < 0 || idx >= ${#DUMP_DIRECTORIES[@]} )); then
    echo "ERROR: selection $n out of range (1..${#DUMP_DIRECTORIES[@]})" >&2
    exit 1
  fi
  SELECTED_DIRS+=("${DUMP_DIRECTORIES[$idx]}")
done

URI="mongodb://localhost:27017"

shopt -s nullglob
for DUMP_DIR in "${SELECTED_DIRS[@]}"; do
  for DUMP_FILE in "${DUMP_DIR}"/*.bson.gz; do
    echo "restoring ${DUMP_FILE} ..."
    # see https://www.mongodb.com/docs/database-tools/mongorestore/
    # notes: --dryRun option exists
    #        you can load into a different database and/or collection by specifying --db and --collection
    mongorestore --uri="${URI}" --gzip "${DUMP_FILE}"
  done
done
