#!/bin/bash

# ----------------------------------------------------------------------------
# Restore Janelia mongodb dump files generated by db-dump-janelia.sh
# to the database running on the current Google Cloud VM container.
#
# You will be prompted to select the dump directory within
# /mnt/disks/mongodb_dump_fs/dump/janelia to restore.

set -e

BASE_DUMP_DIR="/mnt/disks/mongodb_dump_fs/dump"

if [ ! -d "${BASE_DUMP_DIR}" ]; then
  echo "ERROR: ${BASE_DUMP_DIR} not found"
  exit 1
fi

# /mnt/disks/mongodb_dump_fs/dump/janelia/20250201_094952/render/admin__stack_meta_data.bson.gz
mapfile -t DUMP_DIRECTORIES < <(find "${BASE_DUMP_DIR}" -name '*.bson.gz' -type f -exec dirname {} \; | sort -u)
if [ ${#DUMP_DIRECTORIES[@]} -eq 0 ]; then
    echo "ERROR: no dump files found in ${BASE_DUMP_DIR}"
    exit 1
fi

PS3="Enter the number of the dump directory you want to restore: "
select DUMP_DIR in "${DUMP_DIRECTORIES[@]}"; do
  if [ ! -d "${DUMP_DIR}" ]; then
    echo "ERROR: ${DUMP_DIR} not found"
  else
    break
  fi
done

URI="mongodb://localhost:27017"

for DUMP_FILE in "${DUMP_DIR}"/*.bson.gz; do
  echo "restoring ${DUMP_FILE} ..."
  # see https://www.mongodb.com/docs/database-tools/mongorestore/
  # notes: --dryRun option exists
  #        you can load into a different database and/or collection by specifying --db and --collection
  mongorestore --uri="${URI}" --gzip "${DUMP_FILE}"
done
